### ISSUE TITLE
Application layout

### ISSUE THREAD

**Issue by jacomyal** [gephi/gephi-lite#4]
~~The layout will mimick Gephi's, but without the top blocks (browser tabs will replace workspaces). Also, a left vertical bar will offer the lifecycle features, to replace classical desktop applications "File" menu.~~

- [ ] ~~Left bar for lifecycle actions (load, save...)~~
- [ ] ~~Top-left block: #5~~
- [ ] ~~Bottom-left block: #6~~
- [ ] ~~Top-right block: #7~~
- [ ] ~~Middle-right block: #8~~
- [ ] ~~Bottom-right block: #15~~

After long discussions, we decided to go another way.

**Left side**
- [x] On the left, a vertical **toolbar** (that takes the full height) offers the following buttons (each with an icon and a text bellow):
  - [x] #20 (with some margin after)
  - [x] #8 (with some margin after)
  - [x] #5
  - [x] #15
  - [x] #6
- [x] When one of the button above is clicked, the related panel opens as a column just next to the toolbar, and takes the whole height (and can be scrollable)
- [x] On the top right of the panel, there is a `x` button that allows the user to close the panel
- [x] In the toolbar, when a panel is opened, the related tool button is emphasized

**Right side**
- [ ] On the right of the screen, a vertical panel (that takes the whole height) displays the following blocks consecutively:
  - [ ] #7
